
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import SideBar from "@components/UI/SideBar";
import { useEffect, useState } from "react";

export const metadata: Metadata = {
  title: "Setting",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.ico",
  },
};

export default function SettingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <div className={inter.className}>
        <SideBar>{children}</SideBar>
      </div>
  );
}
