import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import ThemeManager from "@theme/ThemeManager";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
  icons: {
    icon: '/images/Logo2.png',
  },
};



export default function NoNavLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeManager>
          <div className="h-[100vh] flex ">{children}</div>
        </ThemeManager>
      </body>
    </html>
  );
}
