
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import { useEffect } from "react";
import ThemeManager from "@theme/ThemeManager";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function NoNavLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeManager></ThemeManager>
          <div className="h-[100vh] flex ">{children}</div>
      </body>
    </html>
  );
}
